MecanicaBeneteli/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace MecanicaBeneteli.WebApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            var titulo = "Mecanica Beneteli";

            ViewData["Title"] = titulo;
            return View();
        }
    }
}

MecanicaBeneteli/Controllers/MenuController.cs
using AutoMapper;
using MecanicaBeneteli.Business.Interfaces.Notificacoes;
using MecanicaBeneteli.Business.Interfaces.Services;
using MecanicaBeneteli.Business.Models;
using MecanicaBeneteli.ViewModel;
using MecanicaBeneteli.WebApp.Extensions.Cookie;
using Microsoft.AspNetCore.Mvc;

namespace MecanicaBeneteli.Controllers
{
    public class MenuController : BaseController
    {
        private readonly IUsuarioService _usuarioService;
        private readonly IEstoqueService _estoqueService;
        private readonly ILeitorCookie _leitorCookie;
        private readonly IMapper _mapper;
        public MenuController(IGeradorCookie geradorCookie,
                               IUsuarioService usuarioService,
                               IEstoqueService estoqueService,
                               ILeitorCookie leitorCookie,
                               IMapper mapper,
                               INotificador notificador)
            : base(geradorCookie, usuarioService, leitorCookie, notificador)
        {
            _usuarioService = usuarioService;
            _estoqueService = estoqueService;
            _leitorCookie = leitorCookie;
            _mapper = mapper;
        }

        [HttpPost]
        public async Task<IActionResult> LoginSucesso(UsuarioViewModel usuarioViewModel)
        {

            try
            {
                var usuario = await _usuarioService.ValidarUsuario(_mapper.Map<Usuario>(usuarioViewModel));
                var dadosUsuario = _mapper.Map<UsuarioViewModel>(usuario);
                // Lógica para quando o usuário é validado com sucesso
                return View("MenuInicio", dadosUsuario);
            }
            catch (Exception ex)
            {
                TempData["Erro"] = ex.Message;
                return RedirectToAction("Index", "Home"); // Ou qualquer outra ação que você queira redirecionar
            }

        }

        [HttpGet]
        public async Task<IActionResult> GerenciarPecas()
        {
            var pecas = await _estoqueService.ConsultarPecas();
            var pecasViewModel = _mapper.Map<List<PecaViewModel>>(pecas);
            return View("CadastrarEstoqueInicio", pecasViewModel);

        }

        [HttpGet]
        public async Task<IActionResult> CadastrarPecasInicio()
        {
            return View("CadastrarPecaInicio");

        }

        [HttpPost]
        public async Task<IActionResult> CadastrarPeca(PecaViewModel pecaViewModel)
        {
            var peca = await _estoqueService.IncluirPeca(_mapper.Map<Peca>(pecaViewModel));

            ViewData["Sucesso"] = "Peça cadastrada com sucesso!";

            return View("CadastrarPecaInicio");


        }

        [HttpGet("ConsultarPecas/{id}", Name = "AlterarPecas")]
        public async Task<IActionResult> ConsultarPecas(int id)
        {

            var peca = await _estoqueService.ConsultarPecaParaAlterar(id);
            var pecaViewModel = _mapper.Map<PecaViewModel>(peca);

            return View("AlterarEstoqueInicio", pecaViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> AlterarPeca(PecaViewModel pecaViewModel)
        {
            var peca = await _estoqueService.AlterarPeca(_mapper.Map<Peca>(pecaViewModel));

            ViewData["Sucesso"] = "Peça alterada com sucesso!";

            return View("AlterarEstoqueInicio");


        }
    }
}

MecanicaBeneteli/Controllers/UsuarioController.cs
using AutoMapper;
using MecanicaBeneteli.Business.Interfaces.Notificacoes;
using MecanicaBeneteli.Business.Interfaces.Services;
using MecanicaBeneteli.Business.Models;
using MecanicaBeneteli.ViewModel;
using MecanicaBeneteli.WebApp.Extensions.Cookie;
using Microsoft.AspNetCore.Mvc;

namespace MecanicaBeneteli.Controllers
{

    public class UsuarioController : BaseController
    {

        private readonly IUsuarioService _usuarioService;
        private readonly ILeitorCookie _leitorCookie;
        private readonly IMapper _mapper;
        public UsuarioController(IGeradorCookie geradorCookie,
                               IUsuarioService usuarioService,
                               ILeitorCookie leitorCookie,
                               IMapper mapper,
                               INotificador notificador)
            : base(geradorCookie, usuarioService, leitorCookie, notificador)
        {
            _usuarioService = usuarioService;
            _leitorCookie = leitorCookie;
            _mapper = mapper;
        }

        [HttpGet]
        public async Task<IActionResult> CadastrarInicio()
        {      

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CadastrarSucesso(UsuarioViewModel usuarioViewModel)
        {
            if (!ModelState.IsValid)
            {
                
                return View("CadastrarInicio", usuarioViewModel);
            }

            var usuario = await _usuarioService.IncluirUsuario(_mapper.Map<Usuario>(usuarioViewModel));

            ViewData["Sucesso"] = "Usuário cadastrado com sucesso!";

            return View("CadastrarInicio");
        }


    }
}

MecanicaBeneteli/Views/Home/Index.cshtml
@model MecanicaBeneteli.ViewModel.UsuarioViewModel


@{
    Layout = null;
}

@{
    var controller = string.Empty;
}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="apple-touch-icon" sizes="180x180" href="~/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="~/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="~/favicon-16x16.png">
    <link rel="manifest" href="~/site.webmanifest">
    <link rel="mask-icon" href="~/safari-pinned-tab.svg" color="#7C7AEC">

    <link href="~/dist/css/style.css" rel="stylesheet" asp-append-version="true" />


    <title>@ViewData["Title"]</title>

</head>
<body>
    <!-- NAVBAR START -->
    <nav class="navbar navbar-expand-lg py-lg-3 navbar-dark">
        <div class="container">

            <!-- logo -->
            <a asp-controller="Usuario" asp-action="CadastrarInicio" title="Clique para criar novo usuário" class="btn btn-light">
                <i class="mdi mdi-account-box mdi-24px"></i>
            </a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
                    aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <i class="mdi mdi-menu"></i>
            </button>

            <!-- menus -->
            <div class="collapse navbar-collapse" id="navbarNavDropdown">

                <!-- right menu -->
                <ul class="navbar-nav ms-auto align-items-center">
                    <li class="nav-item me-0">
                        <!-- Aqui você pode adicionar mais itens do menu se necessário -->
                    </li>
                </ul>

            </div>
        </div>
    </nav>

    <section class="hero-section">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-md-5">
                    <div class="mt-md-4">
                        <h1 class="text-white fw-normal mb-4 mt-3 hero-title">
                            Mecânica Beneteli
                        </h1>

                        <p class="mb-4 font-24 text-white-50">
                            Mantenha suas peças em estoque atualiazadas, de forma inteligente. Faça login para acessar sua conta.
                        </p>
                    </div>
                </div>
                <div class="col-md-5 offset-md-2">
                
                    <div class="text-md-end mt-3 mt-md-0">

                        @if (TempData["Erro"] != null)
                        {
                            <div class="alert alert-danger" role="alert">
                                @TempData["Erro"]
                            </div>
                        }
                        <!-- Formulário de login -->
                        <form asp-controller="Menu" asp-action="LoginSucesso" method="post">



                            <div class="mb-3">
                                <input asp-for="IdUsuario" type="text" class="form-control" id="username" placeholder="Digite seu usuário" required>
                            </div>
                            <div class="mb-3">
                                <input asp-for="Senha" type="password" class="form-control" id="password" placeholder="Digite sua senha" required>
                            </div>
                            <button type="submit" class="btn btn-light">Entrar</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>
</html>