MecanicaBeneteli/Controllers/ManutencaoController.cs
using AutoMapper;
using MecanicaBeneteli.Business.Interfaces.Notificacoes;
using MecanicaBeneteli.Business.Interfaces.Services;
using MecanicaBeneteli.Business.Models;
using MecanicaBeneteli.ViewModel;
using MecanicaBeneteli.WebApp.Extensions.Cookie;
using Microsoft.AspNetCore.Mvc;

namespace MecanicaBeneteli.Controllers
{
    public class ManutencaoController : BaseController
    {
        private readonly IUsuarioService _usuarioService;
        private readonly IEstoqueService _estoqueService;
        private readonly ILeitorCookie _leitorCookie;
        private readonly IMapper _mapper;
        private readonly IManutencaoService _manutencaoService;
        public ManutencaoController(IGeradorCookie geradorCookie,
                               IUsuarioService usuarioService,
                               IEstoqueService estoqueService,
                               ILeitorCookie leitorCookie,
                               IMapper mapper,
                               INotificador notificador,
                               IManutencaoService manutencaoService)
            : base(geradorCookie, usuarioService, leitorCookie, notificador)
        {
            _usuarioService = usuarioService;
            _estoqueService = estoqueService;
            _leitorCookie = leitorCookie;
            _mapper = mapper;
            _manutencaoService = manutencaoService;
        }
        [HttpGet]
        public async Task<IActionResult> ManutencaoInicio()
        {
            var manutencaoViewModel = new ManutencaoViewModel();
            var pecas = await _estoqueService.ConsultarPecas();
            var pecasViewModel = _mapper.Map<List<PecaViewModel>>(pecas);
            manutencaoViewModel.PecaViewModel = pecasViewModel;
            return View("ManutencaoInicio", manutencaoViewModel);

        }

        [HttpPost]
        public async Task<IActionResult> ManutencaoInicio(ManutencaoViewModel manutencaoViewModel)
        {
            var manuetencao = await _manutencaoService.CadastrarManutencao(_mapper.Map<Manutencao>(manutencaoViewModel));

            var manutencaoViewModell = new ManutencaoViewModel();
            var pecas = await _estoqueService.ConsultarPecas();
            var pecasViewModel = _mapper.Map<List<PecaViewModel>>(pecas);
            manutencaoViewModell.PecaViewModel = pecasViewModel;


            ViewData["Sucesso"] = "Manutenção feita com sucesso!";

            return View("ManutencaoInicio", manutencaoViewModell);

        }
    }
}

MecanicaBeneteli/Controllers/MenuController.cs
using AutoMapper;
using MecanicaBeneteli.Business.Interfaces.Notificacoes;
using MecanicaBeneteli.Business.Interfaces.Services;
using MecanicaBeneteli.Business.Models;
using MecanicaBeneteli.ViewModel;
using MecanicaBeneteli.WebApp.Extensions.Cookie;
using Microsoft.AspNetCore.Mvc;

namespace MecanicaBeneteli.Controllers
{
    public class MenuController : BaseController
    {
        private readonly IUsuarioService _usuarioService;
        private readonly IEstoqueService _estoqueService;
        private readonly ILeitorCookie _leitorCookie;
        private readonly IMapper _mapper;
        public MenuController(IGeradorCookie geradorCookie,
                               IUsuarioService usuarioService,
                               IEstoqueService estoqueService,
                               ILeitorCookie leitorCookie,
                               IMapper mapper,
                               INotificador notificador)
            : base(geradorCookie, usuarioService, leitorCookie, notificador)
        {
            _usuarioService = usuarioService;
            _estoqueService = estoqueService;
            _leitorCookie = leitorCookie;
            _mapper = mapper;
        }

        [HttpPost]
        public async Task<IActionResult> LoginSucesso(UsuarioViewModel usuarioViewModel)
        {

            try
            {
                var usuario = await _usuarioService.ValidarUsuario(_mapper.Map<Usuario>(usuarioViewModel));
                var dadosUsuario = _mapper.Map<UsuarioViewModel>(usuario);
                // Lógica para quando o usuário é validado com sucesso
                return View("MenuInicio", dadosUsuario);
            }
            catch (Exception ex)
            {
                TempData["Erro"] = ex.Message;
                return RedirectToAction("Index", "Home"); // Ou qualquer outra ação que você queira redirecionar
            }

        }

        [HttpGet]
        public async Task<IActionResult> GerenciarPecas()
        {
            var pecas = await _estoqueService.ConsultarPecas();
            var pecasViewModel = _mapper.Map<List<PecaViewModel>>(pecas);
            return View("CadastrarEstoqueInicio", pecasViewModel);

        }

        [HttpGet]
        public async Task<IActionResult> CadastrarPecasInicio()
        {
            return View("CadastrarPecaInicio");

        }

        [HttpPost]
        public async Task<IActionResult> CadastrarPeca(PecaViewModel pecaViewModel)
        {
            var peca = await _estoqueService.IncluirPeca(_mapper.Map<Peca>(pecaViewModel));

            ViewData["Sucesso"] = "Peça cadastrada com sucesso!";

            return View("CadastrarPecaInicio");


        }

        [HttpGet("ConsultarPecas/{id}", Name = "AlterarPecas")]
        public async Task<IActionResult> ConsultarPecas(int id)
        {

            var peca = await _estoqueService.ConsultarPecaParaAlterar(id);
            var pecaViewModel = _mapper.Map<PecaViewModel>(peca);

            return View("AlterarEstoqueInicio", pecaViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> AlterarPeca(PecaViewModel pecaViewModel)
        {
            var peca = await _estoqueService.AlterarPeca(_mapper.Map<Peca>(pecaViewModel));

            ViewData["Sucesso"] = "Peça alterada com sucesso!";

            return View("AlterarEstoqueInicio");


        }
    }
}

MecanicaBeneteli/Views/Menu/AlterarEstoqueInicio.cshtml
@model MecanicaBeneteli.ViewModel.PecaViewModel

@{
    Layout = null;
}

<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="Pragma" content="no-cache">
    <meta http-equiv="Expires" content="-1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="apple-touch-icon" sizes="180x180" href="~/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="~/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="~/favicon-16x16.png">
    <link rel="manifest" href="~/site.webmanifest">
    <link rel="mask-icon" href="~/safari-pinned-tab.svg" color="#7C7AEC">

    <link href="~/dist/css/style.css" rel="stylesheet" asp-append-version="true" />
</head>
<body>

@{
    ViewData["Title"] = "Alterar Peças";
}

<div class="container mt-4">
        <h2>Alterar Peças</h2>
        @if (ViewData["Sucesso"] != null)
        {
            <div class="alert alert-success" role="alert">
                @ViewData["Sucesso"]
            </div>
        }
    <form asp-controller="Menu" asp-action="AlterarPeca" method="post">
        <div class="mb-3">
            <label asp-for="Nome" class="form-label">Nome</label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
        </div>
        <div class="mb-3">
                <label asp-for="Marca" class="form-label">Marca</label>
                <input asp-for="Marca" class="form-control" />
                <span asp-validation-for="Marca" class="text-danger"></span>
        </div>
        <div class="mb-3">
                <label asp-for="Modelo" class="form-label">Modelo</label>
                <input asp-for="Modelo" class="form-control" />
                <span asp-validation-for="Modelo" class="text-danger"></span>
        </div>
        <div class="mb-3">
                <label asp-for="Ano" class="form-label">Ano</label>
                <input asp-for="Ano" class="form-control" />
                <span asp-validation-for="Ano" class="text-danger"></span>
        </div>
        <div class="mb-3">
                <label asp-for="Preco" class="form-label">Preco</label>
                <input asp-for="Preco" class="form-control" />
                <span asp-validation-for="Preco" class="text-danger"></span>
        </div>
        <div class="mb-3">
                <label asp-for="Quantidade" class="form-label">Quantidade</label>
                <input asp-for="Quantidade" class="form-control" />
                <span asp-validation-for="Quantidade" class="text-danger"></span>
        </div>
            <input type="hidden" asp-for="Id" />
        <input type="hidden" asp-for="Id" />
            <div class="mt-3">
                <button type="submit" class="btn btn-primary">Alterar</button>
                <a asp-controller="Menu" asp-action="GerenciarPecas" title="Voltar para o gerenciamento de peças" class="btn btn-secondary">
                    <i class="fas fa-arrow-left"></i> Voltar
                </a>
            </div>
    </form>
</div>

    <!-- Inclua os scripts do Bootstrap (opcional, caso utilize funcionalidades que dependam de JavaScript) -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/js/bootstrap.bundle.min.js"></script>
</body>
</html>

MecanicaBeneteli/Views/Menu/CadastrarEstoqueInicio.cshtml
@model List<MecanicaBeneteli.ViewModel.PecaViewModel>

@{
    Layout = null;
}

<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="Pragma" content="no-cache">
    <meta http-equiv="Expires" content="-1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="apple-touch-icon" sizes="180x180" href="~/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="~/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="~/favicon-16x16.png">
    <link rel="manifest" href="~/site.webmanifest">
    <link rel="mask-icon" href="~/safari-pinned-tab.svg" color="#7C7AEC">

    <link href="~/dist/css/style.css" rel="stylesheet" asp-append-version="true" />

</head>

<body>

    <!-- Cabeçalho -->
    <header class="bg-primary text-white py-3">
        <div class="container">
            <div class="row justify-content-between align-items-center">
                <div class="col-auto">
                    <h1 class="h4 mb-0">Bem-vindo, Tiago Beneteli</h1>
                </div>
                <div class="col-auto">
                    <a asp-controller="Home" asp-action="Index" title="Clique para Sair" class="btn btn-light">
                        <i class="mdi mdi-logout mr-2"></i> Sair
                    </a>
                </div>
            </div>
        </div>
    </header>


    <div class="container mt-4">

        <div class="mb-3">
            <a asp-controller="Menu" asp-action="CadastrarPecasInicio" type="button" class="btn btn-primary">Incluir Peça</a>

        </div>


        <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>Marca</th>
                    <th>Modelo</th>
                    <th>Ano</th>
                    <th>Preco</th>
                    <th>Quantidade</th>
                    <th>Alteração</th>

                </tr>
            </thead>
            <tbody>
                @foreach (var peca in Model)
                {
                    <tr>
                        <td>@peca.Nome</td>
                        <td>@peca.Marca</td>
                        <td>@peca.Modelo</td>
                        <td>@peca.Ano</td>
                        <td>@peca.Preco</td>
                        <td>@peca.Quantidade</td>
                        <td class="table-action">
                            <a asp-controller="Menu" asp-action="ConsultarPecas" asp-route-id="@peca.Id" title="Alterar Peça" class="btn btn-primary">
                                <i class="mdi mdi-cog-outline"></i>
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

</body>
</html>

MecanicaBeneteli/Views/Menu/CadastrarPecaInicio.cshtml
@model MecanicaBeneteli.ViewModel.PecaViewModel

@{
    Layout = null;
}

<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="Pragma" content="no-cache">
    <meta http-equiv="Expires" content="-1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="apple-touch-icon" sizes="180x180" href="~/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="~/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="~/favicon-16x16.png">
    <link rel="manifest" href="~/site.webmanifest">
    <link rel="mask-icon" href="~/safari-pinned-tab.svg" color="#7C7AEC">

    <link href="~/dist/css/style.css" rel="stylesheet" asp-append-version="true" />

</head>
<body>

    <!-- Cabeçalho -->
    <header class="bg-primary text-white py-3">
        <div class="container">
            <h1 class="h4 mb-0">Cadastro de Peças</h1>
        </div>
    </header>

    <!-- Conteúdo Principal -->
    <div class="container mt-4">
        <!-- Formulário de Cadastro de Peças -->
        @if (ViewData["Sucesso"] != null)
        {
            <div class="alert alert-success" role="alert">
                @ViewData["Sucesso"]
            </div>
        }
        <form asp-controller="Menu" asp-action="CadastrarPeca" method="post">
            <div class="form-group">
                <label for="nome">Nome:</label>
                <input asp-for="Nome" type="text" class="form-control" id="nome" placeholder="Digite o nome da peça" required>
            </div>
            <div class="form-group">
                <label for="marca">Marca:</label>
                <input asp-for="Marca" type="text" class="form-control" id="marca" placeholder="Digite a marca da peça" required>
            </div>
            <div class="form-group">
                <label for="modelo">Modelo:</label>
                <input asp-for="Modelo" type="text" class="form-control" id="modelo" placeholder="Digite o modelo da peça" required>
            </div>
            <div class="form-group">
                <label for="ano">Ano:</label>
                <input asp-for="Ano" type="text" class="form-control" id="ano" placeholder="Digite o ano da peça">
            </div>
            <div class="form-group">
                <label for="preco">Preço:</label>
                <input asp-for ="Preco" type="text" class="form-control" id="preco" placeholder="Digite o preço da peça" required>
            </div>
            <div class="form-group">
                <label for="quantidade">Quantidade em Estoque:</label>
                <input asp-for="Quantidade" type="text" class="form-control" id="quantidade" placeholder="Digite a quantidade em estoque da peça" required>
            </div>
            @if (!ViewData.ModelState.IsValid)
            {
                <div class="alert alert-danger" role="alert">
                    @Html.ValidationSummary()
                </div>
            }
            <div class="mt-3">
                <button type="submit" class="btn btn-primary">Cadastrar Peça</button>
                <a asp-controller="Menu" asp-action="GerenciarPecas" title="Voltar para o gerenciamento de peças" class="btn btn-secondary">
                    <i class="fas fa-arrow-left"></i> Voltar
                </a>
            </div>
            

            
        </form>
    </div>

    
</body>
</html>

MecanicaBeneteli/Views/Menu/MenuInicio.cshtml
@model MecanicaBeneteli.ViewModel.UsuarioViewModel

@{
    Layout = null;
}

<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="Pragma" content="no-cache">
    <meta http-equiv="Expires" content="-1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="apple-touch-icon" sizes="180x180" href="~/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="~/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="~/favicon-16x16.png">
    <link rel="manifest" href="~/site.webmanifest">
    <link rel="mask-icon" href="~/safari-pinned-tab.svg" color="#7C7AEC">

    <link href="~/dist/css/style.css" rel="stylesheet" asp-append-version="true" />
</head>
<body>
    <header class="bg-primary text-white py-3">
        <div class="container">
            <div class="row justify-content-between align-items-center">
                <div class="col-auto">
                    <h1 class="h4 mb-0">Bem-vindo, Tiago Beneteli</h1>
                </div>
                <div class="col-auto">
                    <a asp-controller="Home" asp-action="Index" title="Clique para Sair" class="btn btn-light">
                        <i class="mdi mdi-logout mr-2"></i> Sair
                    </a>
                </div>
            </div>
        </div>
    </header>
    <div class="container mt-5">
        <h2>Menu da Mecânica</h2>
        <div class="row mt-4">
            <!-- Card de Estoque -->
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Estoque</h5>
                        <p class="card-text">Gerencie o estoque de peças da mecânica</p>
                        <a asp-controller="Menu" asp-action="GerenciarPecas" class="card-link">Gerenciar Peças</a>
                    </div>
                </div>
            </div>
            <!-- Card de Usuário -->
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Usuário</h5>
                        <p class="card-text">Gerencie as configurações do usuário</p>
                        <a href="#" class="card-link">Alterar Senha</a>
                    </div>
                </div>
            </div>
            <!-- Card de Manutenção -->
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Manutenção</h5>
                        <p class="card-text">Agende e gerencie as manutenções de veículos</p>
                        <a asp-controller="Manutencao" asp-action="ManutencaoInicio" class="card-link">Manutenção</a>
                        <a href="#" class="card-link">Histórico de Manutenções</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Incluindo Bootstrap JS (opcional, apenas se necessário) -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>